= 基于架构的软件设计方法及应用

【论点】
基于架构的软件设计（Architecture-Based Software Design，ABSD）方法强调由商业（业务）、质量和功能需求的组合驱动软件架构设计。它强调采用视角和视图来描述软件架构，采用用例和质量属性场景来描述需求。用例描述的是功能需求，质量属性场景描述的是质量需求。
ABSD 是一个**自顶向下，递归细化**的软件开发方法，它以软件系统功能的分解为基础，通过选择架构风格实现质量和商业需求，并强调在架构设计过程中使用软件架构模板。
采用ABSD方法，并不意味着需求抽取和分析活动可以终止，而是应该与设计活动并行。
设计活动可以从项目总体功能框架明确后就开始，因此该方法特别适用于开发一些不能预先决定所有需求的软件系统，如软件产品线系统或长生命周期系统等，也可为需求不能再短时间内明确的软件项目提供指导。

== 摘要
template:系统概括

【论点】
本文以该系统为例，主要论述了基于架构的软件设计方法在项目中的具体应用，
着重从架构需求、架构设计、架构实现三个阶段展开介绍，
在架构需求阶段，通过用户访谈、问卷调查、现场观摩，构造原型的方式全面获取了需求；
在架构设计阶段通过UML模型中的4+1视图来对系统的架构进行建模；
在架构实现阶段，对系统构建进行了获取、开发和组装。

template:摘要末尾总结

* 最终系统顺利上线，获得了用户的一致好评。

== 正文
template:系统详细介绍

【论点】

=== ABSD 开发阶段（需设档，复实演）

采用ABSD方法进行软件开发时，需要经历架构**需**求、架构**设**计、架构文**档**化、架构**复**审、架构**实**现和架构**演**化六个阶段。

. 架构需求阶段需要明确用户对目标软件系统在功能、行为、性能、设计约束等方面的期望。其主要活动包括需求获取、标识构件和架构评审。
** 需求获取活动需要定义开发人员必须实现的软件功能，使得用户能够完成他们的任务，从而满足功能需求。与此同时，还要获得软件质量属性，满足一些非功能性需求
** 标识构件活动首先需要获得系统的基本结构，然后对基本结构进行分组，最后将基本结构进行打包成构件。
** 架构需求评审活动组织一个由系统涉众（用户、系统分析师、架构师、设计实现人员等）组成的小组，对架构需求及相关构件进行审查。审查的主要内容包括所获取的需求是否真实反映了用户需求，构件合并是否合理等。
. 架构设计阶段是一个迭代过程，利用架构需求生成并调整架构决策。主要活动包括提出架构模型、将已标识的构件映射到架构中、分析构件之间的相互作用、产生系统架构和架构设计评审。
. 架构文档化的主要活动是对架构设计进行分析与整理，生成架构规格说明书和测试架构需求的质量设计说明书。
. 在一个主版本的软件架构分析之后，需要安排一次由外部人员（客户代表和领域专家）参加的架构复审。架构复审需要评价架构是否能够满足需求，质量属性需求是否在架构中得以体现、层次是否清晰、构件划分是否合理等。从而标识潜在的风险，及早发现架构设计中的缺陷和错误。
. 架构实现主要是对架构进行实现的过程，主要活动包括架构分析与设计、构件实现、构件组装和系统测试。
. 架构演化阶段主要解决用户在系统开发过程中发生的需求变更问题。主要活动包括架构演化计划、构件变动、更新构件的相互作用、构件的组装与测试和技术评审。

=== 软件开发过程中可能遇到的问题

* 在**架构需求**获取过程中如何捕获架构需求以及对捕获的架构需求进行筛选和优先级排序
* 在架构复审过程中如何解决评审人员的意见不一致问题
* 在架构设计过程中如何合理设计与描述软件架构
* 在**架构实现**过程中如何根据项目组实际情况选择开发语言与开发平台
* 在架构演化过程中如何筛选并处理用户的需求变更，等等


=== 总结
