
= 软件架构风格
== 摘要

我所在企业是国内某电销公司，在2021年4月我司决定开发全新一代数字化电销运营平台。
我担任本次系统开发的架构师，主要负责整个系统的架构设计工作。
该系统要为企业建立与客户稳定畅通的沟通渠道，也要满足企业电商业务特有的变化性，增加营收，方便销售人员进行高效的客转，服务客户，同时是企业日常运营的办公系统，是企业在传统领域进行数字化转型完成数字化办公的重要实践。
本文结合我的实践，以电销平台建设为例，论述软件架构风格。
首先讨论软件架构风格中常见的体系结构风格并阐述了其具体含义，然后详细说明了本次项目所采用的架构风格，并分析了采用该架构风格设计的原因以及实施该架构风格所带来的作用。

== 正文

项目背景
我司从13年在电销行业深耕经营，其业务系统已经过多次重构改造，但在日益增长的客户量，覆盖全国的广告投放下以及多年的数据积累，现有业务系统已不堪重负，企业员工也哀声载道，也逐渐影响到了企业运营效率。正是在这一背景下以及企业高层决定数字化战略转型下，我司决定开发新一代数字化电销平台，即对传统业务系统进行继承，同时开发出符合现代企业数字化电销运营平台。
电销运营平台涵盖了呼叫中心、订单管理、商品管理、营销系统、客户管理、客服中心等几大服务，同时还对接了OA、ERP、WMS、财务系统等常规企业信息系统。建立了适合企业发展的呼叫中心，为客户对企业建立了畅通的沟通渠道，提高了客户对企业的信任度，为客户提供优质的服务；订单管理系统实现了客户订单的管理，库存管理、订单履行，同时为销售人员提供了高效准确的业绩计算方式。营销系统则为电商业务提供了灵活的营销方案支持，增加营收、转化，去库存，拉新及刺激交易等作用。

理论部分
软件架构风格是描述某一特定领域组织方式的惯用模式。体系结构风格反映了领域中众多系统所共有的结构和语义特征，并指导如何将各个模块和子系统有效地组织成一个完整的系统。对软件体系结构风格的研究和实践促进设计的重用，一些经过实践证实的解决方案也可以可靠地用于解决新的问题。
常用的软件架构风格主要分为五大类，分别是数据流风格、调用/返回风格、以数据为中心的体系结构风格、虚拟机风格以及独立构件风格。
数据流风格包括批处理序列和管道-过滤器风格，其特点是每一步都是独立的，顺序执行的，适用于简单的线性流程；
调用/返回风格主要包括主程序-子程序风格、层次型风格、面向对象风格以及客户端/服务器风格，其主要引入了调用/返回机制，本质上是分而治之策略，核心思想是将复杂的大系统分解为一些小系统，以便降低其复杂度，提高可修改性；
以数据为中心的体系结构风格包括仓库风格、超文本系统、数据库系统以及黑板风格，其以数据为中心，善于管理数据信息，适合大量数据的应用场合，适合于复杂的逻辑系统；
虚拟机风格包括解释器风格和基于规则的系统，此类架构具有良好的灵活性；
独立构件风格包括进程通信风格和事件驱动风格，其特点是构件之间不直接通信，它们的个体每一个都是独立的，以便降低耦合度，提高灵活性；
除此之外，还有特定领域软件架构分割、状态转移、REST以及分布式架构风格等等。

实践部分


总结

在系统的架构设计中，我们引入了架构风格的设计思想，实践证明，这种架构设计有效地降低了维护成本，提高了系统地开放性，可拓展性，可复用性和可移植性。 当然还是存在一些问题的，如系统采用HTTP协议，易被非法劫持，可以将协议修改为HTTPS来解决。还有就是旧系统在数据库层面存在很多无效的存储过程和定时任务，对数据库性能造成了影响。对这种高水平高价值的遗留系统问题，我们采用了重构整合的方式进行了改造，保证了系统的延续性。这些都是我在今后的系统架构设计工作中需要注意与改进的地方，也是我日后努力的方向。



== 概述
软件体系结构设计的一个核心目标是重复的体系结构模式，即达到体系结构级别的软件重用。（架构级别的设计模式）

软件体系结构风格是描述某一特定应用领域中系统组织方式的惯用模式。
体系结构风格定义一个系统家族，即一个体系结构定义一个词汇表和一组约束。
词汇表中包含一些构件和连接件类型，而这组约束指出系统是如何将这些构件和连接件组合起来的。
体系结构风格反映了领域中众多系统所共有的结构和语义特性，并指导如何将各个模块和子系统有效地组织成一个完整的系统。
对软件体系结构风格的研究和实践促进设计的重用，一些经过实践证实的解决方案也可以可靠地用于解决新的问题。

== 分类
.数据流体系结构风格
** 批处理：每个处理步骤是一个单独的程序，每一步必须在前一步结束后才能开始，并且数据必须是完整的，以整体的方式传递
** 管道-过滤器：当数据源不断地产生，系统就需要对这些数据进行若干处理（分析、计算、转换等）。将系统分解为几个序贯的处理步骤，步骤之间通过数据流连接，一个步骤的输出是另一个步骤的输入。

.调用/返回体系结构风格：调用/返回机制，分而治之策略。降低复杂度，提高可修改性
** 主程序-子程序：问题划分为若干处理步骤，构件为主程序子程序，连接件为过程调用（交互机制）
** 面向对象：数据的表示方法和它们相应操作封装在一个抽象数据类型或对象中
** 层次型：系统组成一个层次结构，每一层上层提供服务，并作为下层的客户
** 客户端/服务器

.以数据为中心的体系结构风格
** 仓库（Repository)：仓库是存储和维护数据的中心场所
** 黑板：适用于解决复杂的非结构化的问题，能在求解过程中综合运用多种不同知识源，使得问题的表达、组织和求解变得比较容易。

.虚拟机体系结构风格：人为构建一个运行环境，在这个运行环境上，可以解析与运行自定义的一些语言，增加架构的灵活性。
** 解释器
** 规则系统

.独立构件体系结构风格：强调系统中的每个构件都是相对独立的个体，它们之间不直接通信，以降低耦合度，提升灵活性。
** 进程通信：构件是独立的过程，连接件是消息传递，特点：构件是命名过程，消息传递方式：点对点、异步或同步及远程过程调用。
** 事件系统：基于事件的隐式调用风格是构件不直接调用一个过程，而是触发或广播一个或多个事件。






https://zhuanlan.zhihu.com/p/564143827




















