= 论软件架构评估

== 范文

=== 摘要
我所在企业是国内某电销公司，在2021年4月我司决定开发全新一代数字化电销平台。
我担任本次系统开发的架构师，主要负责整个系统的架构设计工作。
该系统既要满足电销领域中的呼叫中心，也要满足企业电商业务，同时是企业日常运营的办公系统，是企业在传统领域进行数字化转型完成数字化办公的重要实践。
本文结合我的实践，以电销平台建设为例，论述软件架构评估。
首先分析了软件架构评估所普遍关注的质量属性并阐述其具体含义，然后详细说明本次项目软件架构评估采用的 ATAM 评估方法、实施过程，评估小组经过对系统中的风险点、敏感点、权衡点进行分析后生成质量效用树。
通过对 ATAM 架构评估保证了电销平台的顺利完成，目前系统已经稳定运行至今，得到了企业高层、用户以及客户的一致好评。

=== 正文

项目背景

过渡部分

本平台基于 J2EE 技术采用 Spring 开发的 B/S 系统，使用微服务架构设计方法，使用 MySQL8.0 关系型数据库，ElasticSearch 搜索引擎，Redis 内存数据库，服务通过 K8S+Docker 技术部署等。

理论部分

软件质量属性是软件架构设计关注的一个重点，在软件架构评估中的质量属性包含性能、可用性、安全性、可修改性、可靠性、易用性、可测试行等，其中前4个质量属性是质量效应树的重要组成部分，具体含义如下；
（1）性能是指系统响应能力，即系统多久才能对某个事件做出响应，或在某段时间内能处理事件的个数。
（2）可用性是指系统能正常运行的时间比。
（3）安全性是指系统除了能对合法用户提供服务，还能阻止非授权用户使用的企图或拒绝服务的能力。
（4）可修改性是指能快速地并以较高性价比对系统进行变更的能力。
（5）可靠性是指软件系统在应用或错误面前、在意外或错误使用情况下维持系统的功能特性的基本能力
（6）易用性是衡量一个用户使用软件产品完成指定任务的难易程度。

常用的架构评估方法有基于问卷调查的评估方法、基于度量的评估方法、基于场景的评估方法。
基于问卷调查方法具有主观性，不太适合本项目；基于度量的评估方法虽然评价比较客观，但需要评价者对系统架构有精确的了解，所以也不太适合本项目；而基于场景的评估方法要求评估者对系统较为了解，评价比较客观，故本项目采用了基于场景的评估方法，基于场景的评估方法又分为架构分析法（SAAM）、架构权衡分析法（ATAM）和成本效益法（CBAM）。本项目根据不同质量属性使用了 ATAM 作为系统架构评估的方法。

实践部分

在进行架构评估是，按照需要确定了评估参与者，
评估小组由接线客服、财务人员、销售人员、仓储人员等组成；
项目决策组由首席信息官、客服经理、销售主管、仓储主管、系统架构师、项目经理、员工代表等组成；
架构涉众还包含项目开发人员、测试人员、运维人员等。
架构评估经历了描述和介绍阶段、调查和分析阶段、测试阶段、报告阶段。下面我分别对这四个阶段进行介绍：

（一）描述和介绍阶段
（二）调查和分析阶段
在该阶段结合场景不同角色的需求分析方都基于各自立场提出了相关需求，需求及质量场景如下：
A）在正常网络负载情况下，系统的接口平均响应时间应在200ms以内。
B）浏览器与服务端的交互，使用SSL证书，实现HTTPS的安全加密访问。
C）系统能够抵御99.99%的黑客攻击。
D）系统应支持账密登录、企业微信登录以及内部OA平台的登录
E）系统出现异常，发生错误时，应在1小时内恢复使用

经过分析总结，我们获得了系统质量属性效用树
（三）测试阶段
（四）报告阶段





结尾


== 知识储备

=== 架构评估过程
=== 架构评估方法

==== 软件架构分析方法 SAAM

SAAM是一种基于场景的系统架构评估方法，最初是用来分析架构的可修改性的，但实践证明也可用于对许多其它质量属性及系统功能的快速评估

=== 架构评估技术

https://blog.csdn.net/ucliaohh/article/details/131865587

软件架构的4+1视图分别是什么？（进场勿开锣4+1视图）
1. 进程视图（对应UML进程视图）：侧重于系统的运行特性。一般用状态图或活动图来表示。
2. 场景视图（对应UML用例视图）：是最重用的需求抽象。一般用用例图表示。
3. 物理视图（对应UML部署视图）：考虑如何将软件映射到硬件上。一般用部署图来表示。
4. 开发视图（对应UML实现视图）：侧重于软件模块的组织和管理（开发环境的静态组织）。一般用构件图来表示。
5. 逻辑视图（对应UML逻辑视图）：描述系统的功能需求（设计的对象模型）。一般用类图来表示。

