= 论软件架构评估

== 范文

=== 摘要
我所在企业是国内某电销公司，在2021年4月我司决定开发全新一代数字化电销运营平台。
我担任本次系统开发的架构师，主要负责整个系统的架构设计工作。
该系统要为企业建立与客户稳定畅通的沟通渠道，也要满足企业电商业务特有的变化性，增加营收，方便销售人员进行高效的客转，服务客户，同时是企业日常运营的办公系统，是企业在传统领域进行数字化转型完成数字化办公的重要实践。
本文结合我的实践，以电销平台建设为例，论述软件架构评估。
首先分析了软件架构评估所普遍关注的质量属性并阐述其具体含义，然后详细说明本次项目软件架构评估采用的 ATAM 评估方法、实施过程，评估小组经过对系统中的风险点、敏感点、权衡点进行分析后生成质量效用树。
通过 ATAM 架构评估保证了电销平台的顺利完成，目前系统已经稳定运行至今，得到了企业高层、用户以及客户的一致好评。

=== 正文

项目背景
我司从13年在电销行业深耕经营，其业务系统已经过多次重构改造，但在日益增长的客户量，覆盖全国的广告投放下以及多年的数据积累，现有业务系统已不堪重负，企业员工也哀声载道，也逐渐影响到了企业运营效率。正是在这一背景下以及企业高层决定数字化战略转型下，我司决定开发新一代数字化电销平台，即对传统业务系统进行继承，同时开发出符合现代企业数字化电销运营平台。
电销运营平台涵盖了呼叫中心、订单管理、商品管理、营销系统、客户管理、客服中心等几大服务，同时还对接了OA、ERP、WMS、财务系统等常规企业信息系统。建立了适合企业发展的呼叫中心，为客户对企业建立了畅通的沟通渠道，提高了客户对企业的信任度，为客户提供优质的服务；订单管理系统实现了客户订单的管理，库存管理、订单履行，同时为销售人员提供了高效准确的业绩计算方式。营销系统则为电商业务提供了灵活的营销方案支持，增加营收、转化，去库存，拉新及刺激交易等作用。

过渡部分

本平台基于 J2EE 技术采用 Spring 开发的 B/S 系统，使用微服务架构设计方法，使用 MySQL8.0 关系型数据库，ElasticSearch 搜索引擎，Redis 内存数据库，服务通过 K8S 容器技术部署等。

理论部分

软件质量属性是软件架构设计关注的一个重点，在软件架构评估中的质量属性包含性能、可用性、安全性、可修改性、可靠性、易用性、可测试行等，其中前4个质量属性是质量效应树的重要组成部分，具体含义如下；
（1）性能是指系统响应能力，即系统多久才能对某个事件做出响应，或在某段时间内能处理事件的个数。
（2）可用性是指系统能正常运行的时间比。
（3）安全性是指系统除了能对合法用户提供服务，还能阻止非授权用户使用的企图或拒绝服务的能力。
（4）可修改性是指能快速地并以较高性价比对系统进行变更的能力。
（5）可靠性是指软件系统在应用或错误面前、在意外或错误使用情况下维持系统的功能特性的基本能力
（6）易用性是衡量一个用户使用软件产品完成指定任务的难易程度。

常用的架构评估方法有基于问卷调查的评估方法、基于度量的评估方法、基于场景的评估方法。
基于问卷调查方法具有主观性，不太适合本项目；基于度量的评估方法虽然评价比较客观，但需要评价者对系统架构有精确的了解，所以也不太适合本项目；而基于场景的评估方法要求评估者对系统较为了解，评价比较客观，故本项目采用了基于场景的评估方法，基于场景的评估方法又分为架构分析法（SAAM）、架构权衡分析法（ATAM）和成本效益法（CBAM）。本项目根据不同质量属性使用了 ATAM 作为系统架构评估的方法。

实践部分

在进行架构评估是，按照需要确定了评估参与者，
评估小组由接线客服、财务人员、销售人员、仓储人员等组成；
项目决策组由首席信息官、客服经理、销售主管、仓储主管、系统架构师、项目经理、员工代表等组成；
架构涉众还包含项目开发人员、测试人员、运维人员等。
架构评估经历了描述和介绍阶段、调查和分析阶段、测试阶段、报告阶段。下面我分别对这四个阶段进行介绍：

（一）描述和介绍阶段
（二）调查和分析阶段
在该阶段结合场景不同角色的需求分析方都基于各自立场提出了相关需求，需求及质量场景如下：
A）在正常网络负载情况下，系统的接口平均响应时间应在200ms以内。
B）浏览器与服务端的交互，使用SSL证书，实现HTTPS的安全加密访问。
C）系统能够抵御99.99%的黑客攻击。
D）系统应支持账密登录、企业微信登录以及内部OA平台的登录
E）系统出现异常，发生错误时，应在1小时内恢复使用

经过分析总结，我们获得了系统质量属性效用树，属于性能的有，属于可用性的有；属于安全性的有；属于可修改性的有；属于可靠性的有。
在这些场景分析中评估人员分析了系统的架构分线、敏感点、权衡点。
架构风险是指系统设计过程中潜在的、存在问题的架构决策所带来的隐患；敏感点是指为了实现某个特定质量属性，一个或多个构件具有的特性；权衡点是指影响多个质量属性的特性，且每个质量属性都属于敏感点。
（三）测试阶段，结合电销行业的特性，经过项目干系人集体讨论后，确定了不同场景的优先级：可用性、可靠性、系统安全性最高，性能、可修改性其次，易用性优先级较低。在保障系统安全方面使用SSL数字证书的HTTPS访问协议，可靠性使用服务单独拆分、分层解耦设计，降低一个模块错误对全系统的影响，使用Spring拦截器对用户操作引起的错误进行统一容错处理。性能方面结合本地缓存、Redis内存数据库作为分布式缓存，并引入RabbitMQ消息队列中间件、数据库采用主从数据库进行读写分离以综合提高。易用性方面采用界面设计的八大黄金法则，设计出多种风格供用户选择。
（四）报告阶段，经过架构的评估，将评估的过程和结果都汇总整理成文档。其中包括架构分析方法文档、不同场景及各自的优先级、质量效用树、风险点决策、非风险点决策、每次评估会议的记录。经过实践证明，实施软件架构评估能正确地识别项目风险点、敏感点、权衡点，提前预判并做好应对措施，做出合理的架构决策，从而提高项目开发的成功率和质量。

结尾

经过7个月的开发，电销平台顺利上线并稳定运行一年多，为销售业绩做出了极大的贡献，节省企业运营成本发挥了重大的作用，得到了企业员工、外部客户的一致好评。





== 知识储备

=== Scenario-Based Architecture Analysis Method（SAAM，基于场景的架构分析方法）

SAAM是一种基于场景的系统架构评估方法，最初是用来分析架构的可修改性的，但实践证明也可用于对许多其它质量属性及系统功能的快速评估。
目的是验证基本的体系结构假设和原则，评估体系结构固有的风险。
SAAM 指导对体系结构的检查，使其主要关注潜在的问题点，如需求冲。
SAAM 不仅能够评估体系结构对与特定系统需求的使用能力，也能用来比较不同的体系结构。
评估参与者：风险承担者、记录人员、软件体系结构设计师。
SAAM 的6个过程：形场、述体、类优、单评、互评、总评
形成场景、描述体系结构、场景的分类和优先级确定、间接场景的单个评估、场景相互作用的评估、总体评估


=== Architecture Tradeoff Analysis Method（ATAM，架构权衡分析法）
评估目的：依据系统质量属性和商业需求评估设计决策的结果。ATAM 希望揭示出架构满足特定质量目标的情况，使我们更清楚地认识到质量目标之间地联系，即如何权衡多个质量目标。
评估参与者：评估小组、项目决策者、构架涉众
评估过程的9个步骤
描述ATAM方法、描述商业动机、描述体系结构、确定体系结构方法、生成质量效应树、分析体系结构方法、讨论和分级场景、描述评估结果


== 架构评估技术

https://blog.csdn.net/ucliaohh/article/details/131865587

软件架构的4+1视图分别是什么？（进场勿开锣4+1视图）

. 进程视图（Process View，对应UML进程视图）：侧重于系统的运行特性。一般用状态图或活动图来表示。
. 场景视图（Scene View，对应UML用例视图）：是最重用的需求抽象。一般用用例图表示。
. 物理视图（Physical View，对应UML部署视图）：考虑如何将软件映射到硬件上。一般用部署图来表示。
. 开发视图（Development View，对应UML实现视图）：侧重于软件模块的组织和管理（开发环境的静态组织）。一般用构件图来表示。
. 逻辑视图（Logic View，对应UML逻辑视图）：描述系统的功能需求（设计的对象模型）。一般用类图来表示。
